### PR TITLE
fixed missing gio and GO 1.19 unsafe

### PR DESCRIPTION
**Pull request by kulak**
Fixed GTK 4 examples to run without compilation errors.  Added missing gio package.

Upgraded version of referenced `go4.org/unsafe/assume-no-moving-gc` package so it allows GO 1.19 as a safe version for GC.

Run `go mod tidy` to cleanup.

### CODE REVIEW

**Comment by diamondburned** [comment]
Thank you! The missing `gio/v2` issue was probably caused by #22, which was made by a now-deleted GitHub user...
